language: generic

services:
  - docker

before_install:
  - docker build -t niicloudoperation/notebook .

script:
  - docker run --rm niicloudoperation/notebook jupyter notebook --version
  - docker run --rm niicloudoperation/notebook papermill '/home/jovyan/tests/97_Test nbextensions.ipynb' /tmp/Result.ipynb
  - docker run --rm niicloudoperation/notebook papermill '/home/jovyan/tests/99_Test python3 env.ipynb' /tmp/Result.ipynb
